### ISSUE TITLE
I'm a bit stuck. Is the project still alive? 

### ISSUE THREAD

**Issue by farislikic** [mpromonet/ws-discovery#6]
Hello, 

I've been trying to get the project to run, but I seem to be stuck. I've also posted a question on stackoverflow, but haven't gotten any answers yet. Here's the link that goes into the specifics of my problem. 

https://stackoverflow.com/questions/76858117/ws-discovery-proxy-ubuntu-gsoap-c

Could you help me out a bit? 

Thanks in advance, and all the best!

**Comment by mpromonet** [comment]
Hi,

I guess you mixed gsoap generated files with other gsoap release. I just build on ubuntu 22.04
```
sudo  apt-get install -y --no-install-recommends ca-certificates git g++ make cmake gsoap libgsoap-dev libssl-dev zlib1g-dev
make
```
The project https://github.com/mpromonet/v4l2onvif is using ws-discovery as a library.

But the proxy was a try, I don't think it is working....

Best Regards,
Michel.

**Comment by farislikic** [comment]
Worked like a charm. Thank you for your quick response and for your help. 

I'll try to play a bit around with it. Do you have any intentions of getting the proxy up and running at some point?

Best regards,
Faris
